server:
  shutdown: graceful
  port: 9090

spring:
  lifecycle:
    timeout-per-shutdown-phase: "60s"

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: ${DB_DDL}

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PWD}


  jackson:
    property-naming-strategy: SNAKE_CASE

jwt:
  secret-key: ${JWT_SECRET}
  access-exp: ${JWT_ACCESS_EXP}
  refresh-exp: ${JWT_REFRESH_EXP}
  header: ${JWT_HEADER}
  prefix: ${JWT_PREFIX}

  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    state: ${NAVER_STATE}

